=pod

=head1 NAME

reddit-wallpaper - Fetch an image from reddit and set it as desktop background

=head1 SYNOPSIS

clipbored [OPTIONS]

=head1 DESCRIPTION

B<reddit-wallpaper> will fetch a random image from reddit.com ether from a specified
subreddit or a random selected from a list of SFW Porn subreddit.

=head1 OPTIONS

  -o, --output         output directory/prefix, if a directory is provided '/' will be appended
  -s, --subreddit      alternative subreddit to fetch the image from
      --mode           may be 'full', 'tile', 'center' or 'aspect' (default)
  -c, --cache          enable image caching
      --no-cache       disabling image caching, even though REDDIT_WALLPAPER_CACHE is set
  -a, --always-new     always fetch a new image (never seen before), this only works if '--cache' is set
      --no-always-new  never check for existence of image
  -h, --help           display this help and exit
  -m, --man            display the manual
  -v  --verbose        be verbose
      --version        output version information and exit

=head1 REQUIREMENTS

B<reddit-wallpaper> requires B<HTTP::Tiny> and B<X11::Wallpaper>

=head1 ENVIRONMENT

You can set the following environment variables:

I<REDDIT_WALLPAPER_OUTPUT> set default output directory/prefix

I<REDDIT_WALLPAPER_SUBREDDITS> should point to a file with a line separated list of subreddits

I<REDDIT_WALLPAPER_CACHE> set default cache policy

I<REDDIT_WALLPAPER_ALWAYS_NEW> set default for I<--alway-new>

=head1 MODE

I<full> fullscreen, stretched to fit

I<tile> tiling image from top left corner

I<center> do not stretch

I<aspect> fullscreen, preserving aspect ratio - the default

For the latter two options, the background for any borders around the image is set to black.

=head1 AUTHOR

Andreas Louv

=head1 REPORTING BUGS

Report bugs to L<use the issue tracker|https://github.com/ginkoms/reddit-wallpaper/issues>.

reddit-wallpaper homepage: L<https://github.com/ginkoms/reddit-wallpaper>

=head1 COPYRIGHT

Copyright 2016 the B<reddit-wallpaper>s L</AUTHOR> as listed above

=head1 LICENSE

This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
